import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import SmoothScroll from "@/components/providers/SmoothScroll";
import Preloader from "@/components/Preloader";
import CustomCursor from "@/components/CustomCursor";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const title = `${siteConfig.name} — ${siteConfig.role}`;
const description = `${siteConfig.bio} Based in ${siteConfig.location}. ${siteConfig.status}.`;

export const metadata: Metadata = {
  metadataBase: new URL("https://raiyanfaisal.com"), // update to your production domain
  title: {
    default: title,
    template: `%s — ${siteConfig.name}`,
  },
  description,
  keywords: [
    "graphic designer",
    "branding designer",
    "logo design",
    "brand identity",
    "Riyadh designer",
    "freelance designer",
  ],
  authors: [{ name: siteConfig.name }],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://raiyanfaisal.com",
    siteName: siteConfig.name,
    title,
    description,
    // og:image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    creator: "@raiyan_graphics",
  },
  icons: {
    icon: [
      { url: "/Raiyan Graphic Blue Ribbon Logo.png", type: "image/svg+xml" },
      { url: "/Raiyan Graphic Blue Ribbon Logo.png" },
    ],
    apple: "/Raiyan Graphic Blue Ribbon Logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="grain">
      <body className="bg-bg font-sans text-fg">
        <SmoothScroll>
          <Preloader />
          <CustomCursor />
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
